# Generated by Django 5.2 on 2025-04-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
