version: '3.9'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fictionalize_me
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  flyway:
    image: flyway/flyway:11.7.2-alpine
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/migrations:/flyway/sql
    command: -connectRetries=60 -url=jdbc:postgresql://postgres:5432/fictionalize_me -user=postgres -password=postgres migrate
    environment:
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true

volumes:
  postgres_data: